### ISSUE TITLE
Bump to 0.26.1

### ISSUE THREAD

**Issue by IvanSanchez** [gobblejs/gobble-rollup#4]
I updated the dependency of rollup to 0.26.1 to get rid of https://github.com/rollup/rollup/issues/618.

@Rich-Harris Can you please `git pull && npm publish` this?

**Comment by Rich-Harris** [comment]
Bumped, thanks – have also added you as an owner of the package on npm so I'm not a bottleneck next time :)

**Comment by IvanSanchez** [comment]
@Rich-Harris Cool :-)
